version: "3.9"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./data/nginx/certs:/etc/nginx/certs
      - ./data/nginx/conf:/etc/nginx/conf.d
      - ./data/nginx/htpasswd:/etc/nginx/htpasswd
  vscode-server:
    build: vscode-server
    volumes:
      - ~/workspace:/root/workspace
    init: true
    depends_on:
      - nginx

